### ISSUE TITLE
Error after delete workspace

### ISSUE THREAD

**Issue by sergioortsm** [mehyaa/vscode-workspace-storage-cleanup#7]
Hello !!

After delete storageworkspaces and run the next command (in a project) i have this error!!

**gulp serve**            

Error on console:
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'c:/Users/user/AppData/Roaming/Code/User/workspaceStorage/b100eb15727ccf88a63720e40501db45/ms-vscode.js-debug-nightly/bootloader.js'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1217:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:447:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:75:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}

Its a node project (spfx sharepoint webpart)

Regards!

**Comment by mehyaa** [comment]
Is this still an issue?

**Comment by mehyaa** [comment]
You shouldn't delete an opened workspace's storage if this was something like that. Some VSCode extensions uses that storage for their workspace related data.

**Comment by mehyaa** [comment]
Error on deleting workspace storage is handled since a couple versions back. Closing this issue 👍🏻
